cmake_minimum_required(VERSION 3.12)
project (soma LANGUAGES C CXX Fortran)
set( BRAINVISA_BVMAKER FALSE )
set(CMAKE_MODULE_PATH "$ENV{PIXI_PROJECT_ROOT}/lib/cmake/brainvisa-cmake:$ENV{PIXI_PROJECT_ROOT}/lib/cmake/brainvisa-cmake/modules" ${CMAKE_MODULE_PATH})

set(DESIRED_QT_VERSION 5)
set(DESIRED_SIP_VERSION 6)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_C_PREPROCESSOR "${_toolchain_prefix}cpp -C" CACHE STRING "C preprocessor command to use" )

find_package( brainvisa-cmake REQUIRED )
BRAINVISA_PROJECT()
enable_testing()

set(soma-io_VERSION_MAJOR ${soma_VERSION_MAJOR})
set(soma-io_VERSION_MINOR ${soma_VERSION_MINOR})
set(soma-io_VERSION_PATCH ${soma_VERSION_PATCH})
set(aims-free_VERSION_MAJOR ${soma_VERSION_MAJOR})
set(aims-free_VERSION_MINOR ${soma_VERSION_MINOR})
set(aims-free_VERSION_PATCH ${soma_VERSION_PATCH})

find_package( PythonInterp REQUIRED )
find_package( python REQUIRED )
find_package( Doxygen )
find_package( Sigc++2 REQUIRED )
find_package( LibXml2 REQUIRED )
find_package( Boost CONFIG REQUIRED )
find_package( OpenSlide )
find_package( Sphinx )
find_package( Blitz REQUIRED )
if( DESIRED_QT_VERSION EQUAL 5 )
  find_package( Qt5Core )
  find_package( Qt5Widgets )
  find_package( Qt5LinguistTools )
  find_package( Qt5Sql )
elseif( DESIRED_QT_VERSION EQUAL 6 )
  find_package( Qt6 COMPONENTS Core Widgets Sql Core5Compat ) # LinguistTools )
endif()
find_package( QtVersion )

find_package( Doxygen )

if( PYTHON_FOUND )
  find_package( Numpy )
  find_package( SIP )
  if( PYTHON_FOUND AND NUMPY_FOUND AND SIP_FOUND )
    BRAINVISA_DEPENDENCY( RUN DEPENDS python RUN )
    BRAINVISA_DEPENDENCY( DEV DEPENDS python DEV )
    BRAINVISA_DEPENDENCY( RUN DEPENDS python-numpy RUN )
    BRAINVISA_DEPENDENCY( RUN DEPENDS python-sip4 RUN )
    BRAINVISA_DEPENDENCY( DEV DEPENDS python-sip4 DEV )
  endif()
endif()

find_package( JPEG )
find_package( TIFF )
find_package( PNG12 )
find_package( DCMTK )
find_package( Jasper QUIET )
find_package( OpenJpeg QUIET )
find_package( MINC )
find_package( EXPAT )
find_package( ZLIB )
find_package( LibKDTree QUIET )


configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/soma-config.cmake.in" "${CMAKE_BINARY_DIR}/cmake/soma-config.cmake")
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/soma-use.cmake.in" "${CMAKE_BINARY_DIR}/cmake/soma-use.cmake" @ONLY)
# TODO: install cmake/soma-config.cmake
# TODO: install cmake/soma-use.cmake

include("${CMAKE_BINARY_DIR}/cmake/soma-config.cmake")
include("${CMAKE_BINARY_DIR}/cmake/soma-use.cmake")

add_subdirectory(brainvisa-share)
add_subdirectory(soma-io)
add_subdirectory(aims-free)
add_subdirectory(aims-gpl)
